---
title: "hw5"
author: "Xiangxiong Feng"
date: "2023-11-15"
output: html_document
---





Problem 2


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(purrr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))


```

```{r}
zip_path = list.files(path = 'zip_file' ,pattern = "\\.csv$", full.names = TRUE)

zip_name = 
  tibble(
    file_name = list.files(path = 'zip_file')
    )

```


``







Problem 3

```{r}
simulate_test = function(mu, n=30, sigma =5, alpha = 0.05) {
  data =
    rnorm(n, mean = mu, sd = sigma)
  
  t_result = 
    t.test(data, alpha = 0.05)|>
    broom::tidy()
  
  estimate = t_result$estimate
  p_value = t_result$p.value
  
  table =
    tibble(
      mu_hat = estimate,
      p_value = p_value,
    )
  
  table
}


simulate_test(mu=2, n=30, sigma =5, alpha = 0.05)


```

```{r}
sim_results_df = 
  expand_grid(
    mu = c(1,2,3,4,5,6),
    iter = 1:5000
  ) |> 
  mutate(
    results = map(mu, simulate_test)
  ) |> 
  unnest(results)|>
  mutate(test_power = case_when(
    p_value <= 0.05 ~ 'rejected',
    p_value > 0.05 ~ 'failed'
  ))


```

```{r}
sim_results_df|>
  group_by(test_power, mu)|>
  filter(test_power == 'rejected')|>
  summarise(n_obs = n())|>
  ggplot(aes(x = mu, y = n_obs)) + geom_point()+geom_line()
```



